

* surf-hippo quick start

** Prerequisites
   - Basic familiarity with Linux 
   - Emacs installed Emacs, not required by handy for Lisp interaction.
   - git installed
   - wget installed
   - unzip installed
					    
** Installation

   1. Get latestest sources and pre-built artifacts

      git clone https://github.com/earl-ducaine/surf-hippo.git .
      wget http://surf-hippo.neurophysics.eu/download/surf-hippo.4.0_alpha.linux.04.04.2017.zip
      mkdir surf-hippo-v40
      unzip surf-hippo.4.0_alpha.linux.04.04.2017.zip -d surf-hippo-v40
      cp -r surf-hippo-v40/bin/* surf-hippo/bin/
      cp -r surf-hippo-v40/cmucl-20d/* surf-hippo/cmucl-20d/
      cd surf-hippo


      The Surf-Hippo User Manual can be found at doc/user-manual.pdf
      and full installation documentation at
      doc/installation/installation.doc.txt


   2. Create (or edit) the .emacs and .bashrc files in your home directory, using the Surf-Hippo examples:

      # Note this appends the contents surf-hippo's .emacs file to
      # your own.  Often times you will want do this by hand to ensure
      # the contents are compatible with your own configuration.
      cat doc/installation/.emacs >> ~/.emacs

      # Likewise for the .bashrc.  Not especially that some commands
      # must be the last command in the ~/.bashrc file.  So ensure
      # surf-hippo commands apear before those.
      cat doc/installation/.bashrc ~/.bashrc

** Running Surf-Hippo under Emacs (SLIME) *

   1. After installing the .emacs configuration as described above, start Emacs:

      emacs

   2. From Emacs, SLIME can be installed via

      M-x package-install <return> slime <return>

      M-x (press <alt> key and the x key in sequence, holding down the
      <alt> while the x is still depressed.

   3. Start SLIME (and Surf-Hippo) from Emacs, via

      M-x slime <return>

      Likewise for running the slime environment.

     *** following has yet to be determined *** 

   4 This will start the Lisp system, where the main interaction is
     via the *slime-repl surf-hippo* Emacs buffer, which shows the prompt
     "SH>".

   5. To start the main menu, type in the top level Surf-Hippo function "(surf)" and hit Return (or Enter):

      SH> (surf)

      or

      Run a demo simulation immediately:

     (topload "circuits/demos/colorized-n120.lisp")
     (run)
   
     In normal use you can ignore the *inferior-lisp* buffer created
     by SLIME.



** Running Surf-Hippo from a terminal window (Linux shell) *

   1. Open a terminal window after installing the .bashrc file as
      described above, and enter the command "surf-hippo". This will
      start the Lisp system, printing a message followed by the Lisp
      prompt (here, the Lisp prompt is "*"):

      surf-hippo

      CMU Common Lisp 20d (20D Unicode), running on lyle-Precision-M4700
      With core: /usr/local/surf-hippo/lib/images/cmucl-20d-image
      Dumped on: Thu, 2017-03-16 11:10:04+01:00 on lyle-Precision-M4700
      Send questions and bug reports to your local CMUCL maintainer, 
      or see <http://www.cmucl.org/support.html>.
      Loaded subsystems:
      Unicode 1.28 with Unicode version 6.1.0
      Python 1.1, target Intel x86/x87
      CLOS based on Gerd's PCL 2010/03/19 15:19:03
      CLX X Library Telent CLX 0.7.3 + CMUCL mods, based on MIT R5.02
      Garnet Version 3.0
      Surf-Hippo Version 4.0, 2/27/17 11:11 am [-1]
      Surf-Hippo Home: surf-hipppo.neurophysics.eu
      
      To start the Surf-Hippo menus enter (SURF) at the Lisp prompt.
      To start the Surf-Hippo demo circuit menu enter (DEMO) at the Lisp prompt.
      For help, read the User Manual in the surf-hippo/doc directory.
      To quit Lisp, enter (QUIT) at the Lisp prompt.


   1. To start the main menu, type in the top level Surf-Hippo function
      "(surf)" and hit Return (or Enter):

      (surf)

      or

      Run a demo simulation immediately:

      (topload "circuits/demos/colorized-n120.lisp")
      (run)

** Next Steps

   A good next step is to read the SH_tutorial.pdf in the doc
   directory.  Next, start with the "Running Surf-Hippo" chapter in
   the User Manual and go from there....
