#!/bin/sh 

mv $SURFHOME/src/cmucl-fixes/*.sparcf  $SURFHOME/bin/cmucl-fixes/
mv $SURFHOME/src/development/*.sparcf $SURFHOME/bin/development/
mv $SURFHOME/src/roylance-clmath/*.sparcf $SURFHOME/bin/roylance-clmath/
mv $SURFHOME/src/garnet-fixes/*.sparcf  $SURFHOME/bin/garnet-fixes/
mv $SURFHOME/src/gui/*.sparcf  $SURFHOME/bin/gui/
mv $SURFHOME/src/hippocampus/*.sparcf $SURFHOME/bin/hippocampus/
mv $SURFHOME/src/sys/*.sparcf  $SURFHOME/bin/sys/
mv $SURFHOME/src/parameters/*.sparcf  $SURFHOME/bin/parameters/
mv $SURFHOME/src/turtle/*.sparcf $SURFHOME/bin/turtle/
mv $SURFHOME/src/retina/*.sparcf $SURFHOME/bin/retina/
mv $SURFHOME/src/visual/*.sparcf $SURFHOME/bin/visual/

